package com.artur.antskip.matcher

import com.artur.antskip.domain.SkipAction

object SkipPhraseBank {
    private val phrases: Map<SkipAction, Set<String>> = mapOf(
        SkipAction.INTRO to normalizedSet(
            "pular abertura",
            "pular intro",
            "pular introducao",
            "saltar intro",
            "saltar abertura",
            "skip intro",
            "skip opening",
            "skip op",
            "skip theme song",
            "skip title sequence",
            "skip intro icon",
            "skip opening icon",
            "skip intro button",
            "skip opening button",
            "skip-intro",
            "skip-opening",
            "saltar intro",
            "saltar introduccion",
            "saltar cabecera",
            "omitir intro",
            "omitir introduccion",
            "saltar abertura",
            "ignorer l intro",
            "passer l intro",
            "passer l ouverture",
            "opening uberspringen",
            "opening uberspringen",
            "intro uberspringen",
            "vorspann uberspringen",
            "intro überspringen",
            "vorspann überspringen",
            "intro overslaan",
            "opening overslaan",
            "salta intro",
            "salta apertura",
            "salta sigla",
            "salta introduzione",
            "salta la sigla",
            "skip intro",
            "intro atla",
            "atla intro",
            "skip intro",
            "op overslaan",
            "pomiń intro",
            "pomin intro",
            "pominac intro",
            "イントロをスキップ",
            "オープニングをスキップ",
            "오프닝 건너뛰기",
            "跳过片头",
            "跳過片頭",
            "跳过开头",
            "跳過開頭",
            "인트로 건너뛰기",
            "giris atla",
            "jenerigi atla",
            "salta intro",
        ),
        SkipAction.RECAP to normalizedSet(
            "pular recap",
            "pular recapitulacao",
            "pular recapitulos",
            "pular resumo",
            "skip recap",
            "skip recap icon",
            "skip recap button",
            "skip-recap",
            "skip recapitulation",
            "saltar resumen",
            "saltar recapitulacion",
            "omitir resumen",
            "omitir recapitulacion",
            "passer le recapitulatif",
            "passer le resume",
            "recap uberspringen",
            "zusammenfassung uberspringen",
            "zusammenfassung überspringen",
            "recap overslaan",
            "samenvatting overslaan",
            "salta riassunto",
            "salta recap",
            "pomin podsumowanie",
            "pomin recap",
            "要約をスキップ",
            "前回のあらすじをスキップ",
            "건너뛰기 요약",
            "요약 건너뛰기",
            "跳过回顾",
            "跳過回顧",
            "ozeti atla",
        ),
        SkipAction.CREDITS to normalizedSet(
            "pular creditos",
            "pular encerramento",
            "pular ending",
            "pular final",
            "pular para o proximo",
            "skip credits",
            "skip ending",
            "skip outro",
            "skip end credits",
            "watch next",
            "skip credits icon",
            "skip ending icon",
            "skip credits button",
            "skip-credits",
            "skip-ending",
            "saltar creditos",
            "saltar final",
            "omitir creditos",
            "salta crediti",
            "salta i crediti",
            "abspann uberspringen",
            "abspann überspringen",
            "ending uberspringen",
            "generique de fin",
            "passer le generique",
            "credits overslaan",
            "aftiteling overslaan",
            "pomin napisy",
            "napisy pomin",
            "クレジットをスキップ",
            "エンディングをスキップ",
            "크레딧 건너뛰기",
            "엔딩 건너뛰기",
            "跳过片尾",
            "跳過片尾",
            "jenerigi atla",
        ),
        SkipAction.PREVIEW to normalizedSet(
            "pular previa",
            "pular pre visualizacao",
            "pular preview",
            "pular trailer",
            "skip preview",
            "skip next preview",
            "skip trailer",
            "skip preview icon",
            "skip-preview",
            "saltar avance",
            "omitir avance",
            "vorschau uberspringen",
            "preview overslaan",
        ),
        SkipAction.NEXT_EPISODE to normalizedSet(
            "proximo",
            "proximo episodio",
            "proximo ep",
            "proxima",
            "proxima parte",
            "reproduzir proximo",
            "assistir proximo",
            "next episode",
            "next",
            "play next",
            "watch next",
            "reproduzir proximo",
            "episodio siguiente",
            "siguiente episodio",
            "ver siguiente",
            "episode suivant",
            "suivant",
            "nachste folge",
            "naechste folge",
            "weiter",
            "volgende aflevering",
            "volgende",
            "prossimo episodio",
            "episodio successivo",
            "następny odcinek",
            "nastepny odcinek",
            "次のエピソード",
            "次の話",
            "다음 화",
            "다음 에피소드",
            "下一集",
            "下一個",
            "sonraki bolum",
            "sonraki",
        ),
    )

    fun match(text: String): SkipAction? {
        if (text.isBlank()) return null
        val relaxed = text.replace('-', ' ')
        return phrases.entries.firstOrNull { (_, patterns) ->
            patterns.any { pattern -> relaxed == pattern || relaxed.contains(pattern) }
        }?.key
    }

    private fun normalizedSet(vararg values: String): Set<String> =
        values.mapTo(linkedSetOf()) { it.normalizeForMatch() }
}
